version: '3.3'
services:
    web:
        build:
            context: ./web
            dockerfile: Dockerfile
        ports:
            - ${NGINX_PORT}:80 # expose ports - HOST:CONTAINER
        volumes:
            - ./app/build/:/usr/share/nginx/html
        links:
            - app
            - backend
    backend:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        volumes:
            - ./server/:/srv/backend
            - /srv/backend/node_modules
        expose:
            - ${BACKEND_PORT}
        environment:
            - PORT=${BACKEND_PORT}
    app:
        build:
            context: ./app
            dockerfile: Dockerfile.dev
        volumes:
            - ./app/:/srv/app
            - /srv/app/node_modules
        depends_on:
            - backend
