#
# ---- Base Node ----
FROM node:9-alpine AS base
# set working directory
WORKDIR /srv/app
# copy project file
COPY package.json yarn.lock ./

#
# ---- Dependencies ----
# install node packages
RUN yarn install

# webpack-dev-server port
# EXPOSE 8080

# container command
CMD ["yarn", "build:watch"]
